name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./gradlew check assemble
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit
      - run: echo "🍏 This job's status is ${{ job.status }}."